---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: httpddaemonset
  labels:
    type: webserver
    author: Tejeswari
spec:
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: myhttpd
      labels:
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 9090
              hostPort: 80
...


