---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: db
    author: Tejeswari
spec:
  containers:
   - name: mydb
     image: postgres
     env:
      - name: POSTGRES_PASSWORD
        value: teju
      - name: POSTGRES_DB
        value: mydb
      - name: POSTGRES_USER
        value: myuser
     ports:
       - containerPort: 5432
         hostPort: 6060
...
