---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    type: webserver
    author: Tejeswari
spec:
   containers: 
    - name: tomee
      image: tomee
      ports: 
       - containerPort: 8080
         hostPort: 5050
...
